export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string | null;
          xp: number | null;
          reputation: number | null;
          achievements: any | null;
          badges: string[] | null;
          updated_at: string | null;
        };
        Insert: {
          id: string;
          username?: string | null;
          xp?: number | null;
          reputation?: number | null;
          achievements?: any | null;
          badges?: string[] | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          username?: string | null;
          xp?: number | null;
          reputation?: number | null;
          achievements?: any | null;
          badges?: string[] | null;
          updated_at?: string | null;
        };
      };
      agent_metadata: {
        Row: {
          id: string;
          slug: string;
          name: string;
          description: string | null;
          logo_url: string | null;
          official_website: string | null;
          country: string | null;
          founded_year: number | null;
          social_links: any | null;
          created_at: string | null;
        };
        Insert: {
          id: string;
          slug: string;
          name: string;
          description?: string | null;
          logo_url?: string | null;
          official_website?: string | null;
          country?: string | null;
          founded_year?: number | null;
          social_links?: any | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          description?: string | null;
          logo_url?: string | null;
          official_website?: string | null;
          country?: string | null;
          founded_year?: number | null;
          social_links?: any | null;
          created_at?: string | null;
        };
      };
      agent_intel: {
        Row: {
          id: string;
          agent_slug: string | null;
          intel_type: string;
          title: string;
          summary: string | null;
          source_url: string;
          published_at: string | null;
          created_at: string | null;
          agent_id_link: string | null;
          image_url: string | null;
        };
        Insert: {
          id: string;
          agent_slug?: string | null;
          intel_type: string;
          title: string;
          summary?: string | null;
          source_url: string;
          published_at?: string | null;
          created_at?: string | null;
          agent_id_link?: string | null;
          image_url?: string | null;
        };
        Update: {
          id?: string;
          agent_slug?: string | null;
          intel_type?: string;
          title?: string;
          summary?: string | null;
          source_url?: string;
          published_at?: string | null;
          created_at?: string | null;
          agent_id_link?: string | null;
          image_url?: string | null;
        };
      };
      agent_model_links: {
        Row: {
          agent_id: string;
          model_id: string;
          created_at: string | null;
        };
        Insert: {
          agent_id: string;
          model_id: string;
          created_at?: string | null;
        };
        Update: {
          agent_id?: string;
          model_id?: string;
          created_at?: string | null;
        };
      };
      agent_posts: {
        Row: {
          id: string;
          agent_id_link: string | null;
          post_type: string | null;
          content: string | null;
          status: string | null;
          created_at: string | null;
        };
        Insert: {
          id: string;
          agent_id_link?: string | null;
          post_type?: string | null;
          content?: string | null;
          status?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          agent_id_link?: string | null;
          post_type?: string | null;
          content?: string | null;
          status?: string | null;
          created_at?: string | null;
        };
      };
      agent_reviews: {
        Row: {
          id: string;
          agent_id_link: string | null;
          title: string | null;
          summary: string | null;
          scores: any | null;
          elo: number | null;
          tags: string | null;
          updated_at: string | null;
        };
        Insert: {
          id: string;
          agent_id_link?: string | null;
          title?: string | null;
          summary?: string | null;
          scores?: any | null;
          elo?: number | null;
          tags?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          agent_id_link?: string | null;
          title?: string | null;
          summary?: string | null;
          scores?: any | null;
          elo?: number | null;
          tags?: string | null;
          updated_at?: string | null;
        };
      };
      agents: {
        Row: {
          id: string;
          name: string;
          slogan: string | null;
          description: string | null;
          metrics: any | null;
          stats: any | null;
          connectivity: any | null;
          tags: string[] | null;
          category: string | null;
          video_poster: string | null;
          persona_img: string | null;
          voice_config: any | null;
          created_at: string | null;
          content_hash: string | null;
          last_verified_at: string | null;
          tactical_badges: string[] | null;
          external_stats: any | null;
          nri_score: number | null;
          full_description: string | null;
          market_analysis: any | null;
          intel_feed: any | null;
          capabilities: string[] | null;
          api_base_url: string | null;
          api_model_name: string | null;
          provider_id: string | null;
          seo_metadata: any | null;
          technical_specs: any | null;
          social_proof: any | null;
          execution_config: any | null;
          related_agents: string[] | null;
          updated_at: string | null;
          status: string | null;
          last_checked_at: string | null;
          official_url: string | null;
          benchmarks: any | null;
          pricing_model_json: any | null;
          framework_stack: string[] | null;
          developer_socials: any | null;
          slug: string | null;
          version: string | null;
          embedding: any | null;
          total_views: number | null;
          execution_count: number | null;
          vendor_id: string | null;
          vendor_slug: string | null;
          specs: any | null;
          entity_type: string | null;
          hot_score: number | null;
          video_url: string | null;
          gif_url: string | null;
          cover_url: string | null;
          media_gallery: any | null;
          audio_sample_url: string | null;
          demo_interaction: any | null;
          display_mode: string | null;
          capability_tags: any | null;
          pricing_model: string | null;
          pricing_details: string | null;
          is_active: boolean | null;
          discovery_source: string | null;
          health_check_failures: number | null;
        };
        Insert: {
          id: string;
          name: string;
          slogan?: string | null;
          description?: string | null;
          metrics?: any | null;
          stats?: any | null;
          connectivity?: any | null;
          tags?: string[] | null;
          category?: string | null;
          video_poster?: string | null;
          persona_img?: string | null;
          voice_config?: any | null;
          created_at?: string | null;
          content_hash?: string | null;
          last_verified_at?: string | null;
          tactical_badges?: string[] | null;
          external_stats?: any | null;
          nri_score?: number | null;
          full_description?: string | null;
          market_analysis?: any | null;
          intel_feed?: any | null;
          capabilities?: string[] | null;
          api_base_url?: string | null;
          api_model_name?: string | null;
          provider_id?: string | null;
          seo_metadata?: any | null;
          technical_specs?: any | null;
          social_proof?: any | null;
          execution_config?: any | null;
          related_agents?: string[] | null;
          updated_at?: string | null;
          status?: string | null;
          last_checked_at?: string | null;
          official_url?: string | null;
          benchmarks?: any | null;
          pricing_model_json?: any | null;
          framework_stack?: string[] | null;
          developer_socials?: any | null;
          slug?: string | null;
          version?: string | null;
          embedding?: any | null;
          total_views?: number | null;
          execution_count?: number | null;
          vendor_id?: string | null;
          vendor_slug?: string | null;
          specs?: any | null;
          entity_type?: string | null;
          hot_score?: number | null;
          video_url?: string | null;
          gif_url?: string | null;
          cover_url?: string | null;
          media_gallery?: any | null;
          audio_sample_url?: string | null;
          demo_interaction?: any | null;
          display_mode?: string | null;
          capability_tags?: any | null;
          pricing_model?: string | null;
          pricing_details?: string | null;
          is_active?: boolean | null;
          discovery_source?: string | null;
          health_check_failures?: number | null;
        };
        Update: {
          id?: string;
          name?: string;
          slogan?: string | null;
          description?: string | null;
          metrics?: any | null;
          stats?: any | null;
          connectivity?: any | null;
          tags?: string[] | null;
          category?: string | null;
          video_poster?: string | null;
          persona_img?: string | null;
          voice_config?: any | null;
          created_at?: string | null;
          content_hash?: string | null;
          last_verified_at?: string | null;
          tactical_badges?: string[] | null;
          external_stats?: any | null;
          nri_score?: number | null;
          full_description?: string | null;
          market_analysis?: any | null;
          intel_feed?: any | null;
          capabilities?: string[] | null;
          api_base_url?: string | null;
          api_model_name?: string | null;
          provider_id?: string | null;
          seo_metadata?: any | null;
          technical_specs?: any | null;
          social_proof?: any | null;
          execution_config?: any | null;
          related_agents?: string[] | null;
          updated_at?: string | null;
          status?: string | null;
          last_checked_at?: string | null;
          official_url?: string | null;
          benchmarks?: any | null;
          pricing_model_json?: any | null;
          framework_stack?: string[] | null;
          developer_socials?: any | null;
          slug?: string | null;
          version?: string | null;
          embedding?: any | null;
          total_views?: number | null;
          execution_count?: number | null;
          vendor_id?: string | null;
          vendor_slug?: string | null;
          specs?: any | null;
          entity_type?: string | null;
          hot_score?: number | null;
          video_url?: string | null;
          gif_url?: string | null;
          cover_url?: string | null;
          media_gallery?: any | null;
          audio_sample_url?: string | null;
          demo_interaction?: any | null;
          display_mode?: string | null;
          capability_tags?: any | null;
          pricing_model?: string | null;
          pricing_details?: string | null;
          is_active?: boolean | null;
          discovery_source?: string | null;
          health_check_failures?: number | null;
        };
      };
      cerebro_traces: {
        Row: {
          id: string;
          session_id: string;
          action_type: string;
          target_slug: string | null;
          search_query: string | null;
          is_semantic: boolean | null;
          execution_provider: string | null;
          created_at: string | null;
        };
        Insert: {
          id: string;
          session_id: string;
          action_type: string;
          target_slug?: string | null;
          search_query?: string | null;
          is_semantic?: boolean | null;
          execution_provider?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          session_id?: string;
          action_type?: string;
          target_slug?: string | null;
          search_query?: string | null;
          is_semantic?: boolean | null;
          execution_provider?: string | null;
          created_at?: string | null;
        };
      };
      lounge_announcements: {
        Row: {
          id: string;
          content: string;
          type: string | null;
          created_at: string | null;
        };
        Insert: {
          id: string;
          content: string;
          type?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          content?: string;
          type?: string | null;
          created_at?: string | null;
        };
      };
    };
  };
}
