
import { Agent } from '../../types';

/**
 * PURE CORE: Agent Transformers
 * Platform-Agnostic: Works in Node.js, Cloudflare Workers, Deno, or Browser.
 * 
 * Transforms raw Agent JSON data into various formats optimized for:
 * - LLM RAG (Markdown)
 * - CLI Hackers (ANSI/ASCII)
 * - Search Engines (JSON-LD)
 */

// --- 1. MARKDOWN TRANSFORMER (Optimized for LLM Context Windows) ---
export function toMarkdown(agent: Agent): string {
  const metrics = agent.metrics || { reasoning: 0, creativity: 0, speed: 0 };
  const connectivity = agent.connectivity || { try_url: 'N/A', iframe_safe: false };
  const stats = agent.stats || { wins: 0, losses: 0, elo: 1000 };

  return `
# ${agent.name} (ID: ${agent.id})
> ${agent.slogan}

## 📋 Overview
${agent.description}

## 📊 Performance Metrics
- **Reasoning**: ${metrics.reasoning}/100
- **Creativity**: ${metrics.creativity}/100
- **Speed**: ${metrics.speed}/100
- **ELO Rating**: ${stats.elo} (Wins: ${stats.wins} | Losses: ${stats.losses})

## 🔗 Connectivity
- **Try It Now**: ${connectivity.try_url}
- **Iframe Safe**: ${connectivity.iframe_safe ? 'Yes' : 'No'}
- **Category**: ${agent.category}

## 🏷️ Tags
${(agent.tags || []).map(tag => `- #${tag}`).join('\n')}

## 🛠️ Technical Specs
- **Context Window**: ${agent.specs?.context_window || 'Unknown'}
- **Model Params**: ${agent.specs?.model_params || 'Unknown'}
- **License**: ${agent.specs?.license || 'Unknown'}
- **Release Date**: ${agent.specs?.release_date || 'Unknown'}

---
*Generated by AIHunter Titanium Relay for LLM Context Injection*
`.trim();
}

// --- 2. CLI TRANSFORMER (Optimized for curl/wget users) ---
export function toCLIString(agent: Agent): string {
  // ANSI Color Codes (Basic)
  const RESET = '\x1b[0m';
  const BOLD = '\x1b[1m';
  const CYAN = '\x1b[36m';
  const GREEN = '\x1b[32m';
  const YELLOW = '\x1b[33m';
  const RED = '\x1b[31m';

  const metrics = agent.metrics || { reasoning: 0, creativity: 0, speed: 0 };
  
  // ASCII Art Header (Minimalist)
  const header = `
   __  __     ______     __  __     ______     __   __     ______   ______    
  /\\ \\_\\ \\   /\\  __ \\   /\\ \\/\\ \\   /\\  ___\\   /\\ "-.\\ \\   /\\__  _\\ /\\  ___\\   
  \\ \\  __ \\  \\ \\  __ \\  \\ \\ \\_\\ \\  \\ \\  __\\   \\ \\ \\-.  \\  \\/_/\\ \\/ \\ \\___  \\  
   \\ \\_\\ \\_\\  \\ \\_\\ \\_\\  \\ \\_____\\  \\ \\_____\\  \\ \\_\\\\"\\_\\    \\ \\_\\  \\/\\_____\\ 
    \\/_/\\/_/   \\/_/\\/_/   \\/_____/   \\/_____/   \\/_/ \\/_/     \\/_/   \\/_____/ 
                                                                              
  `;

  return `
${CYAN}${header}${RESET}
${BOLD}AGENT IDENTITY:${RESET} ${GREEN}${agent.name}${RESET} [${agent.id}]
${YELLOW}"${agent.slogan}"${RESET}

${BOLD}SYSTEM STATUS:${RESET}
----------------------------------------
${CYAN}CATEGORY:${RESET}    ${agent.category}
${CYAN}ELO RATING:${RESET}  ${agent.stats?.elo || 1000}
${CYAN}WIN RATE:${RESET}    ${((agent.stats?.wins || 0) / ((agent.stats?.wins || 0) + (agent.stats?.losses || 0) || 1) * 100).toFixed(1)}%

${BOLD}PERFORMANCE MATRIX:${RESET}
[REASONING]  ${'█'.repeat(Math.floor(metrics.reasoning / 10))} ${metrics.reasoning}%
[CREATIVITY] ${'█'.repeat(Math.floor(metrics.creativity / 10))} ${metrics.creativity}%
[SPEED]      ${'█'.repeat(Math.floor(metrics.speed / 10))} ${metrics.speed}%

${BOLD}CONNECTIVITY:${RESET}
> Endpoint: ${agent.connectivity?.try_url || 'N/A'}

${BOLD}DESCRIPTION:${RESET}
${agent.description}

${RED}>> END OF TRANSMISSION <<${RESET}
`.trim();
}

// --- 3. JSON-LD TRANSFORMER (Optimized for Google/Bing Rich Snippets) ---
export function toJsonLD(agent: Agent): object {
  return {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    "name": agent.name,
    "operatingSystem": "Cloud/Web",
    "applicationCategory": "ArtificialIntelligence",
    "offers": {
      "@type": "Offer",
      "price": "0.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "@type": "AggregateRating",
      "ratingValue": (agent.metrics?.nri_score || 85) / 20, // Normalize 100 scale to 5 stars
      "ratingCount": (agent.stats?.wins || 0) + (agent.stats?.losses || 0) + 10 // Mock count
    },
    "description": agent.description,
    "url": `https://aihunter.io/agent/${agent.id}`,
    "image": agent.video_poster || agent.persona_img,
    "author": {
      "@type": "Organization",
      "name": "AIHunter"
    }
  };
}
